### ISSUE TITLE
Provide some screenshots or a demo instance

### ISSUE THREAD

**Issue by Dragnucs** [anforaProject/anfora#35]
It is a good idea to provide at lease a screenshot of the platform or if possible, and demo instance for people to discover.

**Comment by yabirgb** [comment]
Hi @Dragnucs Here you have a demo video of the last commits to the client https://mastodon.social/@anfora/media (the second post) Defenetly will be a good idea to add some pics to the README, as soon as possible I'll add them

**Comment by yabirgb** [comment]
My idea is to release a demo instance on the first days of september but I just want to ensure some minimums so admins can control the situation

**Comment by yabirgb** [comment]
Uploaded some images and added them to the readme https://github.com/anforaProject/anfora/tree/master/images
