### ISSUE TITLE
Database upgrade

### ISSUE THREAD

**Issue by yalh76** [anforaProject/anfora#52]
when doing an upgrade of the database using: 
`pipenv run python commands.py  -m`

![Capture](https://user-images.githubusercontent.com/30271971/56621079-6a9fdf80-662b-11e9-9d1e-f197654e4d26.PNG)

The upgrade ask a question that can't be automate with a script.

Is there a way to bypass that ?

Like for example `pipenv run python commands.py  -m -y` with the `-y` it do the database upgrade without asking anything ?

**Comment by yabirgb** [comment]
Hi @yalh76 ! The database migration software is [peewee-db-evolve](https://github.com/keredson/peewee-db-evolve/) As far as I know the possibility of skipping the prompt is not documented but you can do it. 

In [this line](https://github.com/anforaProject/anfora/blob/master/src/manage_db.py#L66) when you call `db.evolve()` you have to use `db.evolve(interactive=False)`.

I believe that for manual installations this should prompt as It's a risky operation. My opinions is that we should add an environment variable (maybe `db_evolve_interactive`?) and do

`db.evolve(interactive=os.environ.get('db_evolve_interactive, False))`

Using pipenv you can just ceate an `.env` file  in the root directory and it would load the variables inside as [it is said here](https://pipenv.readthedocs.io/en/latest/advanced/#automatic-loading-of-env)

**Comment by yalh76** [comment]
Instead of using environment variable, I propose to use an argument to command.py

--quiet: to let do the db migration without interaction

https://github.com/anforaProject/anfora/pull/53
